In [45]:
import numpy as np

list1 = []
list1 = [int(i) for i in input("Enter the numbers : \n").split()]
print(list1)
a1 = np.array(list1)
n = max(a1)

Enter the numbers : 
1 2 3
[1, 2, 3]


In [46]:
V = np.array([a1**(n) for n in a1])
print(np.transpose(V))
print("________________________\n")
print(V)

[[ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]]
________________________

[[ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]


In [47]:
list2 = []
X = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
list2 = [int(i) for i in X]
print(list2)
W = 3


[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]


In [48]:
for i in range(len(X) - 2):
    ans = (X[i] + X[i+1] + X[i+2] / W)
    print( "( " ,X[i], " + " ,X[i+1] ," + " ,X[i+2] ," )"," / " ,W, " = ", ans)

(  3  +  5  +  7  )  /  3  =  10.333333333333334
(  5  +  7  +  2  )  /  3  =  12.666666666666666
(  7  +  2  +  8  )  /  3  =  11.666666666666666
(  2  +  8  +  10  )  /  3  =  13.333333333333334
(  8  +  10  +  11  )  /  3  =  21.666666666666668
(  10  +  11  +  65  )  /  3  =  42.66666666666667
(  11  +  65  +  72  )  /  3  =  100.0
(  65  +  72  +  81  )  /  3  =  164.0
(  72  +  81  +  99  )  /  3  =  186.0
(  81  +  99  +  100  )  /  3  =  213.33333333333334
(  99  +  100  +  150  )  /  3  =  249.0
